openapi: '3.0.0'
info:
  description: |-
    This document describes all the APIs that is being developed for the
    task application and the companion website/mobile application.     
  version: 1.0.0
  title: API for task.

tags:
- name: task

paths:

  /api/v1/task:
    post:
      tags:
      -  task
      summary: add the quetion
      operationId: addQuestion
      "x-mojo-to": "controller#create_task"
      description: This operation adds the task.

      
      requestBody:
        description: 'Adds the task'
        required: true
        content:
          application/json:
            schema:
             type: object
             properties:
              user_id:
                type: string
                example: "2a97fb35-40a0-4bc3-aae6-3aad7cbb1221"
                description: "User id"
      responses:
        200:
          description: "Resturant added"
          content:
            application/json:    
              schema:
                type: object
                properties:
                  apiresponse:
                    $ref: '#/components/schemas/ApiResponse'
        400: 
          description: invalid input, object invalid

components:
 schemas:
  ApiResponse:
    type: object
    required:
    - code
    - type
    - severity
    - message
    properties:
      code:
        description: A code for this response. This code shall be referred in the documentation / error glossary.
        type: string
        example: USER_001
      type:
        description: The type of this response.
        type: string
        example: "OK, ERROR, SYSTEM_ERROR"
        enum:
         - OK
         - ERROR
         - SYSTEM_ERROR
      severity:
        description: The nature of the message with respect to the attention it deserves from the end user via UI/UX. eg INFO would mean a positive or expected response to the user. WARN would mean that something awkward happened and user needs to be told and acknowledgement taken.
        type: string
        enum: 
          - DEBUG
          - INFO
          - WARN
          - ERROR
      message:
        description: A user firendly message that the end user can be communicated. The end user is expected to understand this message.
        type: string